version: 0.0
# EC2 instance operating system
os: linux

# Defines how files should be copied from the source location to the target (EC2 instance here)
files:
  - source: /  # Copy all files and directories from the root of the application bundle
    destination: /home/ec2-user/acebook-node-app  # Target location for the copied files

# Set file permissions for scripts
# mode 755: Owner can read/write/execute, others can read/execute
permissions:
  - object: /home/ec2-user/acebook-node-app/scripts/install_nodejs.sh
    mode: 755
    owner: ec2-user
    group: ec2-user
  - object: /home/ec2-user/acebook-node-app/scripts/start_application.sh
    mode: 755
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/install_nodejs.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: ec2-user