name: End-to-end tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x] # Removed newer versions on assumption we'll just use version from repo
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        mongodb-version: ['6.0']

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.11.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - run: npm install
    - run: npm ci

    - name: Cypress install
    - run: npm install cypress

    - name: Cypress run
    - run: npm run build
    - run: npm run test:integration
          
