name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: npm install
      - run: npm ci

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          create: npm run build
          test: npm run test:integration
          
